import localFont from "next/font/local";
import "./globals.css";
import local from "next/font/local";
import Navbar from "@/components/cores/Navbar";
import Head from 'next/head';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const apercuPro = localFont({
  src: "./fonts/ApercuPro-Regular-english.woff2",
  variable: "--font-apercu-pro",
  weight: "100 900"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${apercuPro.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
